import { MarketingPage } from "@/components/marketing/MarketingPage";
import { ctaPrimary, ctaServices } from "@/components/marketing/ctas";

const terms: { term: string; def: string; related?: string }[] = [
  { term: "GEO", def: "Generative engine optimization. Improving how brands, pages, entities, and sources are interpreted, retrieved, cited, and recommended by AI systems.", related: "AI search visibility, citation architecture" },
  { term: "Generative engine optimization", def: "Full term for GEO. The discipline of optimizing for AI-generated answers and retrieval-based search systems.", related: "GEO, AI answers" },
  { term: "AI search visibility", def: "How often, how clearly, and how favorably a brand appears across AI-generated answers and the sources behind them.", related: "Recommendation placement, AI Share of Voice" },
  { term: "AI answers", def: "Responses generated by AI systems such as ChatGPT, Gemini, Perplexity, Copilot, and Google AI Overviews.", related: "AI retrieval layer" },
  { term: "Google AI Overviews", def: "Google's AI-generated answer surface that summarizes results above the classic blue links.", related: "AI answers, search layer" },
  { term: "LLM", def: "Large language model. The class of model that powers most modern AI search and answer systems.", related: "AI retrieval layer" },
  { term: "Retrieval", def: "The step where an AI system selects which sources and content to use when constructing an answer.", related: "Embedding-level GEO, vector optimization" },
  { term: "Prompt cluster", def: "A group of related, high-intent prompts buyers use across the buying journey.", related: "Keyword cluster, recommendation placement" },
  { term: "Keyword cluster", def: "A group of related search queries that share intent and topical context.", related: "Prompt cluster" },
  { term: "Citation architecture", def: "Structured improvement of the owned and third-party sources that support brand authority across Google and AI answers.", related: "Source-layer authority, public evidence layer" },
  { term: "Source-layer authority", def: "The strength, diversity, and accuracy of public sources that AI systems and buyers use to validate a brand.", related: "Citation architecture" },
  { term: "Public evidence layer", def: "The full set of sources outside your website that influence how AI systems and buyers perceive your brand.", related: "Source-layer authority" },
  { term: "Entity clarity", def: "How clearly machines interpret a brand, its products, services, people, and relationships.", related: "Schema, technical SEO" },
  { term: "Schema", def: "Structured data added to pages so machines can interpret their meaning more reliably.", related: "Entity clarity, technical SEO" },
  { term: "Technical SEO", def: "The work that makes a site easy for search engines and AI systems to crawl, index, interpret, and trust.", related: "Schema, entity clarity" },
  { term: "Embedding-level GEO", def: "GEO work focused on how AI systems represent meaning, entities, and relationships during retrieval.", related: "Vector optimization, cosine gap analysis" },
  { term: "Vector optimization", def: "Aligning content with the concepts and intents AI systems use to retrieve answers.", related: "Embedding-level GEO" },
  { term: "Cosine gap analysis", def: "Measuring the semantic distance between a brand and the language, sources, and competitors AI systems associate with its category.", related: "Embedding-level GEO" },
  { term: "Retrieval gap", def: "A specific area where AI systems are not retrieving a brand or its pages despite relevant intent.", related: "Cosine gap analysis" },
  { term: "Recommendation placement", def: "When and where a brand appears in shortlists or recommendations inside AI answers.", related: "AI Share of Voice" },
  { term: "AI Share of Voice", def: "Aggregate measure of brand presence across AI answers within a category and prompt set.", related: "Recommendation placement" },
  { term: "Cited source", def: "A page or source that an AI system retrieves and references when constructing an answer.", related: "Citation architecture" },
  { term: "Corrective-action roadmap", def: "Prioritized plan of fixes across content, technical SEO, citations, and source-layer authority.", related: "Visibility audit" },
  { term: "Visibility audit", def: "Structured diagnostic across Google, AI answers, citations, technical SEO, content, and source layers.", related: "Corrective-action roadmap" },
  { term: "Search layer", def: "Classic search visibility — Google rankings, AI Overviews, technical SEO, schema.", related: "AI retrieval layer, source layer" },
  { term: "AI retrieval layer", def: "AI-generated answers and the systems that produce them, including ChatGPT, Gemini, Perplexity, Copilot.", related: "Search layer" },
  { term: "Source layer", def: "Third-party sources, reviews, comparisons, communities, and publications that influence both buyers and AI systems.", related: "Source-layer authority" },
];

const Glossary = () => (
  <MarketingPage
    meta={{
      title: "GEO and AI Search Visibility Glossary | CiteWorks Studio",
      description:
        "A glossary of GEO, AI search visibility, citation architecture, technical SEO, entity clarity, embedding-level GEO, vector optimization, cosine gap analysis, and source-layer authority terms.",
    }}
    hero={{
      eyebrow: "Resource · Glossary",
      h1: "GEO and AI search visibility glossary.",
      body: "Definitions for the core vocabulary CiteWorks Studio uses across GEO, AI search visibility, citation architecture, and modern search strategy.",
      ctas: [ctaPrimary, { label: "Explore Resources", to: "/resources" }],
    }}
    sections={[
      {
        id: "terms",
        type: "table",
        eyebrow: "Definitions",
        title: "Core terms.",
        headers: ["Term", "Definition", "Related"],
        rows: terms
          .slice()
          .sort((a, b) => a.term.localeCompare(b.term))
          .map((t) => [t.term, t.def, t.related || ""]),
      },
      {
        id: "related",
        type: "links",
        eyebrow: "Related resources",
        title: "Continue learning.",
        links: [
          { label: "What is GEO?", to: "/resources/what-is-geo" },
          { label: "AI Search Visibility", to: "/resources/ai-search-visibility" },
          { label: "Citation Architecture", to: "/resources/citation-architecture" },
          { label: "Embedding-Level GEO", to: "/resources/embedding-level-geo" },
          { label: "Cosine Gap Analysis", to: "/resources/cosine-gap-analysis" },
          { label: "Methodology", to: "/methodology" },
        ],
      },
      {
        id: "final",
        type: "finalCta",
        eyebrow: "Get started",
        title: "Put the vocabulary to work.",
        body: "Start with a Visibility Audit to see how these concepts apply to your brand and category.",
        ctas: [ctaPrimary, ctaServices],
      },
    ]}
  />
);

export default Glossary;
